endpoint = u'hosts'
name = u'Host List'
related_search_fields = [u'modified_by__search',
                         u'job_events__search',
                         u'last_job__search',
                         u'inventory__search',
                         u'inventory_sources__search',
                         u'ad_hoc_commands__search',
                         u'job_host_summaries__search',
                         u'groups__search',
                         u'facts__search',
                         u'ad_hoc_command_events__search',
                         u'job_events_as_primary_host__search',
                         u'smart_inventories__search',
                         u'last_job_host_summary__search',
                         u'created_by__search',
                         u'jobs__search',
                         u'ansible_facts']
parses = [u'application/json']
search_fields = [u'description', u'name']
actions = {u'GET': {u'ansible_facts_modified': {u'filterable': True,
                                                u'help_text': u'The date and time ansible_facts was last modified.',
                                                u'label': u'Ansible facts modified',
                                                u'type': u'datetime'},
                    u'created': {u'filterable': True,
                                 u'help_text': u'Timestamp when this host was created.',
                                 u'label': u'Created',
                                 u'type': u'datetime'},
                    u'description': {u'filterable': True,
                                     u'help_text': u'Optional description of this host.',
                                     u'label': u'Description',
                                     u'type': u'string'},
                    u'enabled': {u'filterable': True,
                                 u'help_text': u'Is this host online and available for running jobs?',
                                 u'label': u'Enabled',
                                 u'type': u'boolean'},
                    u'has_active_failures': {u'filterable': True,
                                             u'help_text': u'Flag indicating whether the last job failed for this host.',
                                             u'label': u'Has active failures',
                                             u'type': u'boolean'},
                    u'has_inventory_sources': {u'filterable': True,
                                               u'help_text': u'Flag indicating whether this host was created/updated from any external inventory sources.',
                                               u'label': u'Has inventory sources',
                                               u'type': u'boolean'},
                    u'id': {u'filterable': True,
                            u'help_text': u'Database ID for this host.',
                            u'label': u'ID',
                            u'type': u'integer'},
                    u'insights_system_id': {u'filterable': True,
                                            u'help_text': u'Red Hat Insights host unique identifier.',
                                            u'label': u'Insights system id',
                                            u'type': u'string'},
                    u'instance_id': {u'filterable': True,
                                     u'help_text': u'The value used by the remote inventory source to uniquely identify the host',
                                     u'label': u'Instance id',
                                     u'type': u'string'},
                    u'inventory': {u'filterable': True,
                                   u'label': u'Inventory',
                                   u'type': u'field'},
                    u'last_job': {u'filterable': True,
                                  u'label': u'Last job',
                                  u'type': u'field'},
                    u'last_job_host_summary': {u'filterable': True,
                                               u'label': u'Last job host summary',
                                               u'type': u'field'},
                    u'modified': {u'filterable': True,
                                  u'help_text': u'Timestamp when this host was last modified.',
                                  u'label': u'Modified',
                                  u'type': u'datetime'},
                    u'name': {u'filterable': True,
                              u'help_text': u'Name of this host.',
                              u'label': u'Name',
                              u'type': u'string'},
                    u'related': {u'help_text': u'Data structure with URLs of related resources.',
                                 u'label': u'Related',
                                 u'type': u'object'},
                    u'summary_fields': {u'help_text': u'Data structure with name/description for related resources.',
                                        u'label': u'Summary fields',
                                        u'type': u'object'},
                    u'type': {u'choices': [[u'host', u'Host']],
                              u'help_text': u'Data type for this host.',
                              u'label': u'Type',
                              u'type': u'choice'},
                    u'url': {u'help_text': u'URL for this host.',
                             u'label': u'Url',
                             u'type': u'string'},
                    u'variables': {u'filterable': True,
                                   u'help_text': u'Host variables in JSON or YAML format.',
                                   u'label': u'Variables',
                                   u'type': u'string'}},
           u'POST': {u'description': {u'default': u'',
                                      u'filterable': True,
                                      u'help_text': u'Optional description of this host.',
                                      u'label': u'Description',
                                      u'required': False,
                                      u'type': u'string'},
                     u'enabled': {u'default': True,
                                  u'filterable': True,
                                  u'help_text': u'Is this host online and available for running jobs?',
                                  u'label': u'Enabled',
                                  u'required': False,
                                  u'type': u'boolean'},
                     u'instance_id': {u'default': u'',
                                      u'filterable': True,
                                      u'help_text': u'The value used by the remote inventory source to uniquely identify the host',
                                      u'label': u'Instance id',
                                      u'max_length': 1024,
                                      u'required': False,
                                      u'type': u'string'},
                     u'inventory': {u'filterable': True,
                                    u'label': u'Inventory',
                                    u'required': True,
                                    u'type': u'field'},
                     u'name': {u'filterable': True,
                               u'help_text': u'Name of this host.',
                               u'label': u'Name',
                               u'max_length': 512,
                               u'required': True,
                               u'type': u'string'},
                     u'variables': {u'default': u'',
                                    u'filterable': True,
                                    u'help_text': u'Host variables in JSON or YAML format.',
                                    u'label': u'Variables',
                                    u'required': False,
                                    u'type': u'string'}}}
renders = [u'application/json', u'text/html']
max_page_size = 200
types = [u'host']
