endpoint = u'groups'
name = u'Group Detail'
parses = [u'application/json']
actions = {u'GET': {u'created': {u'filterable': True,
                                 u'help_text': u'Timestamp when this group was created.',
                                 u'label': u'Created',
                                 u'type': u'datetime'},
                    u'description': {u'filterable': True,
                                     u'help_text': u'Optional description of this group.',
                                     u'label': u'Description',
                                     u'type': u'string'},
                    u'groups_with_active_failures': {u'filterable': True,
                                                     u'help_text': u'Number of child groups within this group that have active failures.',
                                                     u'label': u'Groups with active failures',
                                                     u'min_value': 0,
                                                     u'type': u'integer'},
                    u'has_active_failures': {u'filterable': True,
                                             u'help_text': u'Flag indicating whether this group has any hosts with active failures.',
                                             u'label': u'Has active failures',
                                             u'type': u'boolean'},
                    u'has_inventory_sources': {u'filterable': True,
                                               u'help_text': u'Flag indicating whether this group was created/updated from any external inventory sources.',
                                               u'label': u'Has inventory sources',
                                               u'type': u'boolean'},
                    u'hosts_with_active_failures': {u'filterable': True,
                                                    u'help_text': u'Number of hosts in this group with active failures.',
                                                    u'label': u'Hosts with active failures',
                                                    u'min_value': 0,
                                                    u'type': u'integer'},
                    u'id': {u'filterable': True,
                            u'help_text': u'Database ID for this group.',
                            u'label': u'ID',
                            u'type': u'integer'},
                    u'inventory': {u'filterable': True,
                                   u'label': u'Inventory',
                                   u'type': u'field'},
                    u'modified': {u'filterable': True,
                                  u'help_text': u'Timestamp when this group was last modified.',
                                  u'label': u'Modified',
                                  u'type': u'datetime'},
                    u'name': {u'filterable': True,
                              u'help_text': u'Name of this group.',
                              u'label': u'Name',
                              u'type': u'string'},
                    u'related': {u'help_text': u'Data structure with URLs of related resources.',
                                 u'label': u'Related',
                                 u'type': u'object'},
                    u'summary_fields': {u'help_text': u'Data structure with name/description for related resources.',
                                        u'label': u'Summary fields',
                                        u'type': u'object'},
                    u'total_groups': {u'filterable': True,
                                      u'help_text': u'Total number of child groups contained within this group.',
                                      u'label': u'Total groups',
                                      u'min_value': 0,
                                      u'type': u'integer'},
                    u'total_hosts': {u'filterable': True,
                                     u'help_text': u'Total number of hosts directly or indirectly in this group.',
                                     u'label': u'Total hosts',
                                     u'min_value': 0,
                                     u'type': u'integer'},
                    u'type': {u'choices': [[u'group', u'Group']],
                              u'help_text': u'Data type for this group.',
                              u'label': u'Type',
                              u'type': u'choice'},
                    u'url': {u'help_text': u'URL for this group.',
                             u'label': u'Url',
                             u'type': u'string'},
                    u'variables': {u'filterable': True,
                                   u'help_text': u'Group variables in JSON or YAML format.',
                                   u'label': u'Variables',
                                   u'type': u'string'}},
           u'PUT': {u'description': {u'default': u'',
                                     u'filterable': True,
                                     u'help_text': u'Optional description of this group.',
                                     u'label': u'Description',
                                     u'required': False,
                                     u'type': u'string'},
                    u'name': {u'filterable': True,
                              u'help_text': u'Name of this group.',
                              u'label': u'Name',
                              u'max_length': 512,
                              u'required': True,
                              u'type': u'string'},
                    u'variables': {u'default': u'',
                                   u'filterable': True,
                                   u'help_text': u'Group variables in JSON or YAML format.',
                                   u'label': u'Variables',
                                   u'required': False,
                                   u'type': u'string'}}}
renders = [u'application/json', u'text/html']
types = [u'group']
