endpoint = u'applications'
name = u'OAuth 2 Applications'
related_search_fields = [u'user__search', u'organization__search']
parses = [u'application/json']
search_fields = [u'name', u'description']
actions = {u'GET': {u'authorization_grant_type': {u'choices': [[u'authorization-code',
                                                                u'Authorization code'],
                                                               [u'implicit',
                                                                   u'Implicit'],
                                                               [u'password',
                                                                u'Resource owner password-based'],
                                                               [u'client-credentials',
                                                                u'Client credentials']],
                                                  u'filterable': True,
                                                  u'help_text': u'The Grant type the user must use for acquire tokens for this application.',
                                                  u'label': u'Authorization Grant Type',
                                                  u'type': u'choice'},
                    u'client_id': {u'filterable': True,
                                   u'label': u'Client id',
                                   u'type': u'string'},
                    u'client_secret': {u'filterable': True,
                                       u'help_text': u'Used for more stringent verification of access to an application when creating a token.',
                                       u'label': u'Client Secret',
                                       u'type': u'string'},
                    u'client_type': {u'choices': [[u'confidential', u'Confidential'],
                                                  [u'public', u'Public']],
                                     u'filterable': True,
                                     u'help_text': u'Set to Public or Confidential depending on how secure the client device is.',
                                     u'label': u'Client Type',
                                     u'type': u'choice'},
                    u'created': {u'filterable': True,
                                 u'help_text': u'Timestamp when this application was created.',
                                 u'label': u'Created',
                                 u'type': u'datetime'},
                    u'description': {u'filterable': True,
                                     u'help_text': u'Optional description of this application.',
                                     u'label': u'Description',
                                     u'type': u'string'},
                    u'id': {u'filterable': True,
                            u'help_text': u'Database ID for this application.',
                            u'label': u'Id',
                            u'type': u'integer'},
                    u'modified': {u'help_text': u'Timestamp when this application was last modified.',
                                  u'label': u'Modified',
                                  u'type': u'datetime'},
                    u'name': {u'filterable': True,
                              u'help_text': u'Name of this application.',
                              u'label': u'Name',
                              u'type': u'string'},
                    u'organization': {u'filterable': True,
                                      u'help_text': u'Organization containing this application.',
                                      u'label': u'Organization',
                                      u'type': u'field'},
                    u'redirect_uris': {u'filterable': True,
                                       u'help_text': u'Allowed URIs list, space separated',
                                       u'label': u'Redirect URIs',
                                       u'type': u'string'},
                    u'related': {u'help_text': u'Data structure with URLs of related resources.',
                                 u'label': u'Related',
                                 u'type': u'object'},
                    u'skip_authorization': {u'filterable': True,
                                            u'help_text': u'Set True to skip authorization step for completely trusted applications.',
                                            u'label': u'Skip Authorization',
                                            u'type': u'boolean'},
                    u'summary_fields': {u'help_text': u'Data structure with name/description for related resources.',
                                        u'label': u'Summary fields',
                                        u'type': u'object'},
                    u'type': {u'choices': [[u'o_auth2_application', u'Application']],
                              u'help_text': u'Data type for this application.',
                              u'label': u'Type',
                              u'type': u'choice'},
                    u'url': {u'help_text': u'URL for this application.',
                             u'label': u'Url',
                             u'type': u'string'}},
           u'POST': {u'authorization_grant_type': {u'choices': [[u'authorization-code',
                                                                 u'Authorization code'],
                                                                [u'implicit',
                                                                 u'Implicit'],
                                                                [u'password',
                                                                 u'Resource owner password-based'],
                                                                [u'client-credentials',
                                                                 u'Client credentials']],
                                                   u'filterable': True,
                                                   u'help_text': u'The Grant type the user must use for acquire tokens for this application.',
                                                   u'label': u'Authorization Grant Type',
                                                   u'required': True,
                                                   u'type': u'choice'},
                     u'client_type': {u'choices': [[u'confidential', u'Confidential'],
                                                   [u'public', u'Public']],
                                      u'filterable': True,
                                      u'help_text': u'Set to Public or Confidential depending on how secure the client device is.',
                                      u'label': u'Client Type',
                                      u'required': True,
                                      u'type': u'choice'},
                     u'description': {u'default': u'',
                                      u'filterable': True,
                                      u'help_text': u'Optional description of this application.',
                                      u'label': u'Description',
                                      u'required': False,
                                      u'type': u'string'},
                     u'name': {u'filterable': True,
                               u'help_text': u'Name of this application.',
                               u'label': u'Name',
                               u'max_length': 255,
                               u'required': False,
                               u'type': u'string'},
                     u'organization': {u'filterable': True,
                                       u'help_text': u'Organization containing this application.',
                                       u'label': u'Organization',
                                       u'required': False,
                                       u'type': u'field'},
                     u'redirect_uris': {u'filterable': True,
                                        u'help_text': u'Allowed URIs list, space separated',
                                        u'label': u'Redirect URIs',
                                        u'required': False,
                                        u'type': u'string'},
                     u'skip_authorization': {u'default': False,
                                             u'filterable': True,
                                             u'help_text': u'Set True to skip authorization step for completely trusted applications.',
                                             u'label': u'Skip Authorization',
                                             u'required': False,
                                             u'type': u'boolean'}}}
renders = [u'application/json', u'text/html']
max_page_size = 200
types = [u'o_auth2_application']
