endpoint = u'job_templates'
name = u'Job Template List'
related_search_fields = [u'instance_groups__search',
                         u'modified_by__search',
                         u'workflowjobnodes__search',
                         u'project__search',
                         u'last_job__search',
                         u'inventory__search',
                         u'notification_templates_any__search',
                         u'labels__search',
                         u'notification_templates_error__search',
                         u'unifiedjob_unified_jobs__search',
                         u'notification_templates_success__search',
                         u'next_schedule__search',
                         u'current_job__search',
                         u'workflowjobtemplatenodes__search',
                         u'jobs__search',
                         u'created_by__search',
                         u'credentials__search',
                         u'unifiedjobtemplate_ptr__search',
                         u'schedules__search']
parses = [u'application/json']
search_fields = [u'description', u'name']
actions = {u'GET': {u'allow_simultaneous': {u'filterable': True,
                                            u'label': u'Allow simultaneous',
                                            u'type': u'boolean'},
                    u'ask_credential_on_launch': {u'filterable': True,
                                                  u'label': u'Ask credential on launch',
                                                  u'type': u'boolean'},
                    u'ask_diff_mode_on_launch': {u'filterable': True,
                                                 u'label': u'Ask diff mode on launch',
                                                 u'type': u'boolean'},
                    u'ask_inventory_on_launch': {u'filterable': True,
                                                 u'label': u'Ask inventory on launch',
                                                 u'type': u'boolean'},
                    u'ask_job_type_on_launch': {u'filterable': True,
                                                u'label': u'Ask job type on launch',
                                                u'type': u'boolean'},
                    u'ask_limit_on_launch': {u'filterable': True,
                                             u'label': u'Ask limit on launch',
                                             u'type': u'boolean'},
                    u'ask_skip_tags_on_launch': {u'filterable': True,
                                                 u'label': u'Ask skip tags on launch',
                                                 u'type': u'boolean'},
                    u'ask_tags_on_launch': {u'filterable': True,
                                            u'label': u'Ask tags on launch',
                                            u'type': u'boolean'},
                    u'ask_variables_on_launch': {u'filterable': True,
                                                 u'label': u'Ask variables on launch',
                                                 u'type': u'boolean'},
                    u'ask_verbosity_on_launch': {u'filterable': True,
                                                 u'label': u'Ask verbosity on launch',
                                                 u'type': u'boolean'},
                    u'become_enabled': {u'filterable': True,
                                        u'label': u'Become enabled',
                                        u'type': u'boolean'},
                    u'cloud_credential': {u'help_text': u'This resource has been deprecated and will be removed in a future release',
                                          u'label': u'Cloud credential',
                                          u'min_value': 1,
                                          u'type': u'integer'},
                    u'created': {u'filterable': True,
                                 u'help_text': u'Timestamp when this job template was created.',
                                 u'label': u'Created',
                                 u'type': u'datetime'},
                    u'credential': {u'help_text': u'This resource has been deprecated and will be removed in a future release',
                                    u'label': u'Credential',
                                    u'min_value': 1,
                                    u'type': u'integer'},
                    u'custom_virtualenv': {u'filterable': True,
                                           u'help_text': u'Local absolute file path containing a custom Python virtualenv to use',
                                           u'label': u'Custom virtualenv',
                                           u'type': u'string'},
                    u'description': {u'filterable': True,
                                     u'help_text': u'Optional description of this job template.',
                                     u'label': u'Description',
                                     u'type': u'string'},
                    u'diff_mode': {u'filterable': True,
                                   u'help_text': u'If enabled, textual changes made to any templated files on the host are shown in the standard output',
                                   u'label': u'Diff mode',
                                   u'type': u'boolean'},
                    u'extra_vars': {u'filterable': True,
                                    u'label': u'Extra vars',
                                    u'type': u'string'},
                    u'force_handlers': {u'filterable': True,
                                        u'label': u'Force handlers',
                                        u'type': u'boolean'},
                    u'forks': {u'filterable': True,
                               u'label': u'Forks',
                               u'max_value': 2147483647,
                               u'min_value': 0,
                               u'type': u'integer'},
                    u'host_config_key': {u'filterable': True,
                                         u'label': u'Host config key',
                                         u'type': u'string'},
                    u'id': {u'filterable': True,
                            u'help_text': u'Database ID for this job template.',
                            u'label': u'ID',
                            u'type': u'integer'},
                    u'inventory': {u'filterable': True,
                                   u'label': u'Inventory',
                                   u'type': u'field'},
                    u'job_tags': {u'filterable': True,
                                  u'label': u'Job tags',
                                  u'type': u'string'},
                    u'job_type': {u'choices': [[u'run', u'Run'], [u'check', u'Check']],
                                  u'filterable': True,
                                  u'label': u'Job type',
                                  u'type': u'choice'},
                    u'last_job_failed': {u'filterable': True,
                                         u'label': u'Last job failed',
                                         u'type': u'boolean'},
                    u'last_job_run': {u'filterable': True,
                                      u'label': u'Last job run',
                                      u'type': u'datetime'},
                    u'limit': {u'filterable': True,
                               u'label': u'Limit',
                               u'type': u'string'},
                    u'modified': {u'filterable': True,
                                  u'help_text': u'Timestamp when this job template was last modified.',
                                  u'label': u'Modified',
                                  u'type': u'datetime'},
                    u'name': {u'filterable': True,
                              u'help_text': u'Name of this job template.',
                              u'label': u'Name',
                              u'type': u'string'},
                    u'network_credential': {u'help_text': u'This resource has been deprecated and will be removed in a future release',
                                            u'label': u'Network credential',
                                            u'min_value': 1,
                                            u'type': u'integer'},
                    u'next_job_run': {u'filterable': True,
                                      u'label': u'Next job run',
                                      u'type': u'datetime'},
                    u'playbook': {u'filterable': True,
                                  u'label': u'Playbook',
                                  u'type': u'string'},
                    u'project': {u'filterable': True,
                                 u'label': u'Project',
                                 u'type': u'field'},
                    u'related': {u'help_text': u'Data structure with URLs of related resources.',
                                 u'label': u'Related',
                                 u'type': u'object'},
                    u'skip_tags': {u'filterable': True,
                                   u'label': u'Skip tags',
                                   u'type': u'string'},
                    u'start_at_task': {u'filterable': True,
                                       u'label': u'Start at task',
                                       u'type': u'string'},
                    u'status': {u'choices': [[u'new', u'New'],
                                             [u'pending', u'Pending'],
                                             [u'waiting', u'Waiting'],
                                             [u'running', u'Running'],
                                             [u'successful', u'Successful'],
                                             [u'failed', u'Failed'],
                                             [u'error', u'Error'],
                                             [u'canceled', u'Canceled'],
                                             [u'never updated', u'Never Updated']],
                                u'filterable': True,
                                u'label': u'Status',
                                u'type': u'choice'},
                    u'summary_fields': {u'help_text': u'Data structure with name/description for related resources.',
                                        u'label': u'Summary fields',
                                        u'type': u'object'},
                    u'survey_enabled': {u'filterable': True,
                                        u'label': u'Survey enabled',
                                        u'type': u'boolean'},
                    u'timeout': {u'filterable': True,
                                 u'help_text': u'The amount of time (in seconds) to run before the task is canceled.',
                                 u'label': u'Timeout',
                                 u'max_value': 2147483647,
                                 u'min_value': -2147483648,
                                 u'type': u'integer'},
                    u'type': {u'choices': [[u'job_template', u'Job Template']],
                              u'help_text': u'Data type for this job template.',
                              u'label': u'Type',
                              u'type': u'choice'},
                    u'url': {u'help_text': u'URL for this job template.',
                             u'label': u'Url',
                             u'type': u'string'},
                    u'use_fact_cache': {u'filterable': True,
                                        u'help_text': u'If enabled, Tower will act as an Ansible Fact Cache Plugin; persisting facts at the end of a playbook run to the database and caching facts for use by Ansible.',
                                        u'label': u'Use fact cache',
                                        u'type': u'boolean'},
                    u'vault_credential': {u'help_text': u'This resource has been deprecated and will be removed in a future release',
                                          u'label': u'Vault credential',
                                          u'min_value': 1,
                                          u'type': u'integer'},
                    u'verbosity': {u'choices': [[0, u'0 (Normal)'],
                                                [1, u'1 (Verbose)'],
                                                [2, u'2 (More Verbose)'],
                                                [3, u'3 (Debug)'],
                                                [4, u'4 (Connection Debug)'],
                                                [5, u'5 (WinRM Debug)']],
                                   u'filterable': True,
                                   u'label': u'Verbosity',
                                   u'type': u'choice'}},
           u'POST': {u'allow_simultaneous': {u'default': False,
                                             u'filterable': True,
                                             u'label': u'Allow simultaneous',
                                             u'required': False,
                                             u'type': u'boolean'},
                     u'ask_credential_on_launch': {u'default': False,
                                                   u'filterable': True,
                                                   u'label': u'Ask credential on launch',
                                                   u'required': False,
                                                   u'type': u'boolean'},
                     u'ask_diff_mode_on_launch': {u'default': False,
                                                  u'filterable': True,
                                                  u'label': u'Ask diff mode on launch',
                                                  u'required': False,
                                                  u'type': u'boolean'},
                     u'ask_inventory_on_launch': {u'default': False,
                                                  u'filterable': True,
                                                  u'label': u'Ask inventory on launch',
                                                  u'required': False,
                                                  u'type': u'boolean'},
                     u'ask_job_type_on_launch': {u'default': False,
                                                 u'filterable': True,
                                                 u'label': u'Ask job type on launch',
                                                 u'required': False,
                                                 u'type': u'boolean'},
                     u'ask_limit_on_launch': {u'default': False,
                                              u'filterable': True,
                                              u'label': u'Ask limit on launch',
                                              u'required': False,
                                              u'type': u'boolean'},
                     u'ask_skip_tags_on_launch': {u'default': False,
                                                  u'filterable': True,
                                                  u'label': u'Ask skip tags on launch',
                                                  u'required': False,
                                                  u'type': u'boolean'},
                     u'ask_tags_on_launch': {u'default': False,
                                             u'filterable': True,
                                             u'label': u'Ask tags on launch',
                                             u'required': False,
                                             u'type': u'boolean'},
                     u'ask_variables_on_launch': {u'default': False,
                                                  u'filterable': True,
                                                  u'label': u'Ask variables on launch',
                                                  u'required': False,
                                                  u'type': u'boolean'},
                     u'ask_verbosity_on_launch': {u'default': False,
                                                  u'filterable': True,
                                                  u'label': u'Ask verbosity on launch',
                                                  u'required': False,
                                                  u'type': u'boolean'},
                     u'become_enabled': {u'default': False,
                                         u'filterable': True,
                                         u'label': u'Become enabled',
                                         u'required': False,
                                         u'type': u'boolean'},
                     u'cloud_credential': {u'default': None,
                                           u'help_text': u'This resource has been deprecated and will be removed in a future release',
                                           u'label': u'Cloud credential',
                                           u'min_value': 1,
                                           u'required': False,
                                           u'type': u'integer'},
                     u'credential': {u'default': None,
                                     u'help_text': u'This resource has been deprecated and will be removed in a future release',
                                     u'label': u'Credential',
                                     u'min_value': 1,
                                     u'required': False,
                                     u'type': u'integer'},
                     u'custom_virtualenv': {u'default': None,
                                            u'filterable': True,
                                            u'help_text': u'Local absolute file path containing a custom Python virtualenv to use',
                                            u'label': u'Custom virtualenv',
                                            u'max_length': 100,
                                            u'required': False,
                                            u'type': u'string'},
                     u'description': {u'default': u'',
                                      u'filterable': True,
                                      u'help_text': u'Optional description of this job template.',
                                      u'label': u'Description',
                                      u'required': False,
                                      u'type': u'string'},
                     u'diff_mode': {u'default': False,
                                    u'filterable': True,
                                    u'help_text': u'If enabled, textual changes made to any templated files on the host are shown in the standard output',
                                    u'label': u'Diff mode',
                                    u'required': False,
                                    u'type': u'boolean'},
                     u'extra_vars': {u'default': u'',
                                     u'filterable': True,
                                     u'label': u'Extra vars',
                                     u'required': False,
                                     u'type': u'string'},
                     u'force_handlers': {u'default': False,
                                         u'filterable': True,
                                         u'label': u'Force handlers',
                                         u'required': False,
                                         u'type': u'boolean'},
                     u'forks': {u'default': 0,
                                u'filterable': True,
                                u'label': u'Forks',
                                u'max_value': 2147483647,
                                u'min_value': 0,
                                u'required': False,
                                u'type': u'integer'},
                     u'host_config_key': {u'default': u'',
                                          u'filterable': True,
                                          u'label': u'Host config key',
                                          u'max_length': 1024,
                                          u'required': False,
                                          u'type': u'string'},
                     u'inventory': {u'filterable': True,
                                    u'label': u'Inventory',
                                    u'required': False,
                                    u'type': u'field'},
                     u'job_tags': {u'default': u'',
                                   u'filterable': True,
                                   u'label': u'Job tags',
                                   u'max_length': 1024,
                                   u'required': False,
                                   u'type': u'string'},
                     u'job_type': {u'choices': [[u'run', u'Run'], [u'check', u'Check']],
                                   u'default': u'run',
                                   u'filterable': True,
                                   u'label': u'Job type',
                                   u'required': False,
                                   u'type': u'choice'},
                     u'limit': {u'default': u'',
                                u'filterable': True,
                                u'label': u'Limit',
                                u'max_length': 1024,
                                u'required': False,
                                u'type': u'string'},
                     u'name': {u'filterable': True,
                               u'help_text': u'Name of this job template.',
                               u'label': u'Name',
                               u'max_length': 512,
                               u'required': True,
                               u'type': u'string'},
                     u'network_credential': {u'default': None,
                                             u'help_text': u'This resource has been deprecated and will be removed in a future release',
                                             u'label': u'Network credential',
                                             u'min_value': 1,
                                             u'required': False,
                                             u'type': u'integer'},
                     u'playbook': {u'default': u'',
                                   u'filterable': True,
                                   u'label': u'Playbook',
                                   u'max_length': 1024,
                                   u'required': False,
                                   u'type': u'string'},
                     u'project': {u'filterable': True,
                                  u'label': u'Project',
                                  u'required': False,
                                  u'type': u'field'},
                     u'skip_tags': {u'default': u'',
                                    u'filterable': True,
                                    u'label': u'Skip tags',
                                    u'max_length': 1024,
                                    u'required': False,
                                    u'type': u'string'},
                     u'start_at_task': {u'default': u'',
                                        u'filterable': True,
                                        u'label': u'Start at task',
                                        u'max_length': 1024,
                                        u'required': False,
                                        u'type': u'string'},
                     u'survey_enabled': {u'default': False,
                                         u'filterable': True,
                                         u'label': u'Survey enabled',
                                         u'required': False,
                                         u'type': u'boolean'},
                     u'timeout': {u'default': 0,
                                  u'filterable': True,
                                  u'help_text': u'The amount of time (in seconds) to run before the task is canceled.',
                                  u'label': u'Timeout',
                                  u'max_value': 2147483647,
                                  u'min_value': -2147483648,
                                  u'required': False,
                                  u'type': u'integer'},
                     u'use_fact_cache': {u'default': False,
                                         u'filterable': True,
                                         u'help_text': u'If enabled, Tower will act as an Ansible Fact Cache Plugin; persisting facts at the end of a playbook run to the database and caching facts for use by Ansible.',
                                         u'label': u'Use fact cache',
                                         u'required': False,
                                         u'type': u'boolean'},
                     u'vault_credential': {u'default': None,
                                           u'help_text': u'This resource has been deprecated and will be removed in a future release',
                                           u'label': u'Vault credential',
                                           u'min_value': 1,
                                           u'required': False,
                                           u'type': u'integer'},
                     u'verbosity': {u'choices': [[0, u'0 (Normal)'],
                                                 [1, u'1 (Verbose)'],
                                                 [2, u'2 (More Verbose)'],
                                                 [3, u'3 (Debug)'],
                                                 [4, u'4 (Connection Debug)'],
                                                 [5, u'5 (WinRM Debug)']],
                                    u'default': 0,
                                    u'filterable': True,
                                    u'label': u'Verbosity',
                                    u'required': False,
                                    u'type': u'choice'}}}
renders = [u'application/json', u'text/html']
max_page_size = 200
types = [u'job_template']
