endpoint = u'activity_stream'
name = u'Activity Stream List'
max_page_size = 200
parses = [u'application/json']
search_fields = [u'changes']
actions = {u'GET': {u'changes': {u'filterable': True,
                                 u'help_text': u'A summary of the new and changed values when an object is created, updated, or deleted',
                                 u'label': u'Changes',
                                 u'type': u'field'},
                    u'id': {u'filterable': True,
                            u'help_text': u'Database ID for this activity stream.',
                            u'label': u'ID',
                            u'type': u'integer'},
                    u'object1': {u'filterable': True,
                                 u'help_text': u'For create, update, and delete events this is the object type that was affected. For associate and disassociate events this is the object type associated or disassociated with object2.',
                                 u'label': u'Object1',
                                 u'type': u'string'},
                    u'object2': {u'filterable': True,
                                 u'help_text': u'Unpopulated for create, update, and delete events. For associate and disassociate events this is the object type that object1 is being associated with.',
                                 u'label': u'Object2',
                                 u'type': u'string'},
                    u'object_association': {u'label': u'Object association',
                                            u'type': u'field'},
                    u'operation': {u'choices': [[u'create', u'Entity Created'],
                                                [u'update', u'Entity Updated'],
                                                [u'delete', u'Entity Deleted'],
                                                [u'associate',
                                                 u'Entity Associated with another Entity'],
                                                [u'disassociate',
                                                 u'Entity was Disassociated with another Entity']],
                                   u'filterable': True,
                                   u'help_text': u'The action taken with respect to the given object(s).',
                                   u'label': u'Operation',
                                   u'type': u'choice'},
                    u'related': {u'help_text': u'Data structure with URLs of related resources.',
                                 u'label': u'Related',
                                 u'type': u'object'},
                    u'summary_fields': {u'help_text': u'Data structure with name/description for related resources.',
                                        u'label': u'Summary fields',
                                        u'type': u'object'},
                    u'timestamp': {u'filterable': True,
                                   u'label': u'Timestamp',
                                   u'type': u'datetime'},
                    u'type': {u'choices': [[u'activity_stream', u'Activity Stream']],
                              u'help_text': u'Data type for this activity stream.',
                              u'label': u'Type',
                              u'type': u'choice'},
                    u'url': {u'help_text': u'URL for this activity stream.',
                             u'label': u'Url',
                             u'type': u'string'}}}
renders = [u'application/json', u'text/html']
types = [u'activity_stream']
