endpoint = u'organizations'
name = u'Organization List'
related_search_fields = [u'instance_groups__search',
                         u'modified_by__search',
                         u'teams__search',
                         u'notification_templates__search',
                         u'applications__search',
                         u'projects__search',
                         u'notification_templates_any__search',
                         u'notification_templates_error__search',
                         u'inventories__search',
                         u'credentials__search',
                         u'notification_templates_success__search',
                         u'custom_inventory_scripts__search',
                         u'created_by__search',
                         u'labels__search',
                         u'workflows__search']
parses = [u'application/json']
search_fields = [u'description', u'name']
actions = {u'GET': {u'created': {u'filterable': True,
                                 u'help_text': u'Timestamp when this organization was created.',
                                 u'label': u'Created',
                                 u'type': u'datetime'},
                    u'custom_virtualenv': {u'filterable': True,
                                           u'help_text': u'Local absolute file path containing a custom Python virtualenv to use',
                                           u'label': u'Custom virtualenv',
                                           u'type': u'string'},
                    u'description': {u'filterable': True,
                                     u'help_text': u'Optional description of this organization.',
                                     u'label': u'Description',
                                     u'type': u'string'},
                    u'id': {u'filterable': True,
                            u'help_text': u'Database ID for this organization.',
                            u'label': u'ID',
                            u'type': u'integer'},
                    u'modified': {u'filterable': True,
                                  u'help_text': u'Timestamp when this organization was last modified.',
                                  u'label': u'Modified',
                                  u'type': u'datetime'},
                    u'name': {u'filterable': True,
                              u'help_text': u'Name of this organization.',
                              u'label': u'Name',
                              u'type': u'string'},
                    u'related': {u'help_text': u'Data structure with URLs of related resources.',
                                 u'label': u'Related',
                                 u'type': u'object'},
                    u'summary_fields': {u'help_text': u'Data structure with name/description for related resources.',
                                        u'label': u'Summary fields',
                                        u'type': u'object'},
                    u'type': {u'choices': [[u'organization', u'Organization']],
                              u'help_text': u'Data type for this organization.',
                              u'label': u'Type',
                              u'type': u'choice'},
                    u'url': {u'help_text': u'URL for this organization.',
                             u'label': u'Url',
                             u'type': u'string'}},
           u'POST': {u'custom_virtualenv': {u'default': None,
                                            u'filterable': True,
                                            u'help_text': u'Local absolute file path containing a custom Python virtualenv to use',
                                            u'label': u'Custom virtualenv',
                                            u'max_length': 100,
                                            u'required': False,
                                            u'type': u'string'},
                     u'description': {u'default': u'',
                                      u'filterable': True,
                                      u'help_text': u'Optional description of this organization.',
                                      u'label': u'Description',
                                      u'required': False,
                                      u'type': u'string'},
                     u'name': {u'filterable': True,
                               u'help_text': u'Name of this organization.',
                               u'label': u'Name',
                               u'max_length': 512,
                               u'required': True,
                               u'type': u'string'}}}
renders = [u'application/json', u'text/html']
max_page_size = 200
types = [u'organization']
