endpoint = u'notification_templates'
name = u'Notification Template List'
related_search_fields = [u'modified_by__search',
                         u'notifications__search',
                         u'organization_notification_templates_for_errors__search',
                         u'organization_notification_templates_for_any__search',
                         u'organization_notification_templates_for_success__search',
                         u'unifiedjobtemplate_notification_templates_for_errors__search',
                         u'unifiedjobtemplate_notification_templates_for_any__search',
                         u'unifiedjobtemplate_notification_templates_for_success__search',
                         u'created_by__search',
                         u'organization__search']
parses = [u'application/json']
search_fields = [u'description', u'name']
actions = {u'GET': {u'created': {u'filterable': True,
                                 u'help_text': u'Timestamp when this notification template was created.',
                                 u'label': u'Created',
                                 u'type': u'datetime'},
                    u'description': {u'filterable': True,
                                     u'help_text': u'Optional description of this notification template.',
                                     u'label': u'Description',
                                     u'type': u'string'},
                    u'id': {u'filterable': True,
                            u'help_text': u'Database ID for this notification template.',
                            u'label': u'ID',
                            u'type': u'integer'},
                    u'modified': {u'filterable': True,
                                  u'help_text': u'Timestamp when this notification template was last modified.',
                                  u'label': u'Modified',
                                  u'type': u'datetime'},
                    u'name': {u'filterable': True,
                              u'help_text': u'Name of this notification template.',
                              u'label': u'Name',
                              u'type': u'string'},
                    u'notification_configuration': {u'email': {u'host': {u'label': u'Host',
                                                                         u'type': u'string'},
                                                               u'password': {u'label': u'Password',
                                                                             u'type': u'password'},
                                                               u'port': {u'label': u'Port',
                                                                         u'type': u'int'},
                                                               u'recipients': {u'label': u'Recipient List',
                                                                               u'type': u'list'},
                                                               u'sender': {u'label': u'Sender Email',
                                                                           u'type': u'string'},
                                                               u'use_ssl': {u'label': u'Use SSL',
                                                                            u'type': u'bool'},
                                                               u'use_tls': {u'label': u'Use TLS',
                                                                            u'type': u'bool'},
                                                               u'username': {u'label': u'Username',
                                                                             u'type': u'string'}},
                                                    u'filterable': True,
                                                    u'hipchat': {u'api_url': {u'label': u'API Url (e.g: https://mycompany.hipchat.com)',
                                                                              u'type': u'string'},
                                                                 u'color': {u'label': u'Notification Color',
                                                                            u'type': u'string'},
                                                                 u'message_from': {u'label': u'Label to be shown with notification',
                                                                                   u'type': u'string'},
                                                                 u'notify': {u'label': u'Notify room',
                                                                             u'type': u'bool'},
                                                                 u'rooms': {u'label': u'Destination Rooms',
                                                                            u'type': u'list'},
                                                                 u'token': {u'label': u'Token',
                                                                            u'type': u'password'}},
                                                    u'irc': {u'nickname': {u'label': u'IRC Nick',
                                                                           u'type': u'string'},
                                                             u'password': {u'label': u'IRC Server Password',
                                                                           u'type': u'password'},
                                                             u'port': {u'label': u'IRC Server Port',
                                                                       u'type': u'int'},
                                                             u'server': {u'label': u'IRC Server Address',
                                                                         u'type': u'string'},
                                                             u'targets': {u'label': u'Destination Channels or Users',
                                                                          u'type': u'list'},
                                                             u'use_ssl': {u'label': u'SSL Connection',
                                                                          u'type': u'bool'}},
                                                    u'label': u'Notification configuration',
                                                    u'mattermost': {u'mattermost_no_verify_ssl': {u'label': u'Verify SSL',
                                                                                                  u'type': u'bool'},
                                                                    u'mattermost_url': {u'label': u'Target URL',
                                                                                        u'type': u'string'}},
                                                    u'pagerduty': {u'client_name': {u'label': u'Client Identifier',
                                                                                    u'type': u'string'},
                                                                   u'service_key': {u'label': u'API Service/Integration Key',
                                                                                    u'type': u'string'},
                                                                   u'subdomain': {u'label': u'Pagerduty subdomain',
                                                                                  u'type': u'string'},
                                                                   u'token': {u'label': u'API Token',
                                                                              u'type': u'password'}},
                                                    u'rocketchat': {u'rocketchat_no_verify_ssl': {u'label': u'Verify SSL',
                                                                                                  u'type': u'bool'},
                                                                    u'rocketchat_url': {u'label': u'Target URL',
                                                                                        u'type': u'string'}},
                                                    u'slack': {u'channels': {u'label': u'Destination Channels',
                                                                             u'type': u'list'},
                                                               u'token': {u'label': u'Token',
                                                                          u'type': u'password'}},
                                                    u'twilio': {u'account_sid': {u'label': u'Account SID',
                                                                                 u'type': u'string'},
                                                                u'account_token': {u'label': u'Account Token',
                                                                                   u'type': u'password'},
                                                                u'from_number': {u'label': u'Source Phone Number',
                                                                                 u'type': u'string'},
                                                                u'to_numbers': {u'label': u'Destination SMS Numbers',
                                                                                u'type': u'list'}},
                                                    u'type': u'field',
                                                    u'webhook': {u'headers': {u'label': u'HTTP Headers',
                                                                              u'type': u'object'},
                                                                 u'url': {u'label': u'Target URL',
                                                                          u'type': u'string'}}},
                    u'notification_type': {u'choices': [[u'email', u'Email'],
                                                        [u'slack', u'Slack'],
                                                        [u'twilio', u'Twilio'],
                                                        [u'pagerduty',
                                                            u'Pagerduty'],
                                                        [u'hipchat', u'HipChat'],
                                                        [u'webhook', u'Webhook'],
                                                        [u'mattermost',
                                                            u'Mattermost'],
                                                        [u'rocketchat',
                                                            u'Rocket.Chat'],
                                                        [u'irc', u'IRC']],
                                           u'filterable': True,
                                           u'label': u'Notification type',
                                           u'type': u'choice'},
                    u'organization': {u'filterable': True,
                                      u'label': u'Organization',
                                      u'type': u'field'},
                    u'related': {u'help_text': u'Data structure with URLs of related resources.',
                                 u'label': u'Related',
                                 u'type': u'object'},
                    u'summary_fields': {u'help_text': u'Data structure with name/description for related resources.',
                                        u'label': u'Summary fields',
                                        u'type': u'object'},
                    u'type': {u'choices': [[u'notification_template',
                                            u'Notification Template']],
                              u'help_text': u'Data type for this notification template.',
                              u'label': u'Type',
                              u'type': u'choice'},
                    u'url': {u'help_text': u'URL for this notification template.',
                             u'label': u'Url',
                             u'type': u'string'}},
           u'POST': {u'description': {u'default': u'',
                                      u'filterable': True,
                                      u'help_text': u'Optional description of this notification template.',
                                      u'label': u'Description',
                                      u'required': False,
                                      u'type': u'string'},
                     u'name': {u'filterable': True,
                               u'help_text': u'Name of this notification template.',
                               u'label': u'Name',
                               u'max_length': 512,
                               u'required': True,
                               u'type': u'string'},
                     u'notification_configuration': {u'default': {},
                                                     u'email': {u'host': {u'label': u'Host',
                                                                          u'type': u'string'},
                                                                u'password': {u'label': u'Password',
                                                                              u'type': u'password'},
                                                                u'port': {u'label': u'Port',
                                                                          u'type': u'int'},
                                                                u'recipients': {u'label': u'Recipient List',
                                                                                u'type': u'list'},
                                                                u'sender': {u'label': u'Sender Email',
                                                                            u'type': u'string'},
                                                                u'use_ssl': {u'label': u'Use SSL',
                                                                             u'type': u'bool'},
                                                                u'use_tls': {u'label': u'Use TLS',
                                                                             u'type': u'bool'},
                                                                u'username': {u'label': u'Username',
                                                                              u'type': u'string'}},
                                                     u'filterable': True,
                                                     u'hipchat': {u'api_url': {u'label': u'API Url (e.g: https://mycompany.hipchat.com)',
                                                                               u'type': u'string'},
                                                                  u'color': {u'label': u'Notification Color',
                                                                             u'type': u'string'},
                                                                  u'message_from': {u'label': u'Label to be shown with notification',
                                                                                    u'type': u'string'},
                                                                  u'notify': {u'label': u'Notify room',
                                                                              u'type': u'bool'},
                                                                  u'rooms': {u'label': u'Destination Rooms',
                                                                             u'type': u'list'},
                                                                  u'token': {u'label': u'Token',
                                                                             u'type': u'password'}},
                                                     u'irc': {u'nickname': {u'label': u'IRC Nick',
                                                                            u'type': u'string'},
                                                              u'password': {u'label': u'IRC Server Password',
                                                                            u'type': u'password'},
                                                              u'port': {u'label': u'IRC Server Port',
                                                                        u'type': u'int'},
                                                              u'server': {u'label': u'IRC Server Address',
                                                                          u'type': u'string'},
                                                              u'targets': {u'label': u'Destination Channels or Users',
                                                                           u'type': u'list'},
                                                              u'use_ssl': {u'label': u'SSL Connection',
                                                                           u'type': u'bool'}},
                                                     u'label': u'Notification configuration',
                                                     u'mattermost': {u'mattermost_no_verify_ssl': {u'label': u'Verify SSL',
                                                                                                   u'type': u'bool'},
                                                                     u'mattermost_url': {u'label': u'Target URL',
                                                                                         u'type': u'string'}},
                                                     u'pagerduty': {u'client_name': {u'label': u'Client Identifier',
                                                                                     u'type': u'string'},
                                                                    u'service_key': {u'label': u'API Service/Integration Key',
                                                                                     u'type': u'string'},
                                                                    u'subdomain': {u'label': u'Pagerduty subdomain',
                                                                                   u'type': u'string'},
                                                                    u'token': {u'label': u'API Token',
                                                                               u'type': u'password'}},
                                                     u'required': False,
                                                     u'rocketchat': {u'rocketchat_no_verify_ssl': {u'label': u'Verify SSL',
                                                                                                   u'type': u'bool'},
                                                                     u'rocketchat_url': {u'label': u'Target URL',
                                                                                         u'type': u'string'}},
                                                     u'slack': {u'channels': {u'label': u'Destination Channels',
                                                                              u'type': u'list'},
                                                                u'token': {u'label': u'Token',
                                                                           u'type': u'password'}},
                                                     u'twilio': {u'account_sid': {u'label': u'Account SID',
                                                                                  u'type': u'string'},
                                                                 u'account_token': {u'label': u'Account Token',
                                                                                    u'type': u'password'},
                                                                 u'from_number': {u'label': u'Source Phone Number',
                                                                                  u'type': u'string'},
                                                                 u'to_numbers': {u'label': u'Destination SMS Numbers',
                                                                                 u'type': u'list'}},
                                                     u'type': u'field',
                                                     u'webhook': {u'headers': {u'label': u'HTTP Headers',
                                                                               u'type': u'object'},
                                                                  u'url': {u'label': u'Target URL',
                                                                           u'type': u'string'}}},
                     u'notification_type': {u'choices': [[u'email', u'Email'],
                                                         [u'slack', u'Slack'],
                                                         [u'twilio', u'Twilio'],
                                                         [u'pagerduty',
                                                          u'Pagerduty'],
                                                         [u'hipchat', u'HipChat'],
                                                         [u'webhook', u'Webhook'],
                                                         [u'mattermost',
                                                             u'Mattermost'],
                                                         [u'rocketchat',
                                                             u'Rocket.Chat'],
                                                         [u'irc', u'IRC']],
                                            u'filterable': True,
                                            u'label': u'Notification type',
                                            u'required': True,
                                            u'type': u'choice'},
                     u'organization': {u'filterable': True,
                                       u'label': u'Organization',
                                       u'required': True,
                                       u'type': u'field'}}}
renders = [u'application/json', u'text/html']
max_page_size = 200
types = [u'notification_template']
