endpoint = u'me'
name = u'Me'
related_search_fields = [u'roles__search',
                         u'main_oauth2accesstoken__search',
                         u'enterprise_auth__search',
                         u'main_oauth2application__search',
                         u'oauth2_provider_refreshtoken__search',
                         u'profile__search',
                         u'activity_stream__search',
                         u'oauth2_provider_grant__search',
                         u'social_auth__search']
parses = [u'application/json']
search_fields = [u'username', u'first_name', u'last_name', u'email']
actions = {u'GET': {u'created': {u'help_text': u'Timestamp when this user was created.',
                                 u'label': u'Created',
                                 u'type': u'datetime'},
                    u'email': {u'filterable': True,
                               u'label': u'Email address',
                               u'type': u'string'},
                    u'external_account': {u'help_text': u'Set if the account is managed by an external service',
                                          u'label': u'External account',
                                          u'type': u'field'},
                    u'first_name': {u'filterable': True,
                                    u'label': u'First name',
                                    u'type': u'string'},
                    u'id': {u'filterable': True,
                            u'help_text': u'Database ID for this user.',
                            u'label': u'ID',
                            u'type': u'integer'},
                    u'is_superuser': {u'filterable': True,
                                      u'help_text': u'Designates that this user has all permissions without explicitly assigning them.',
                                      u'label': u'Superuser status',
                                      u'type': u'boolean'},
                    u'is_system_auditor': {u'label': u'Is system auditor',
                                           u'type': u'boolean'},
                    u'last_name': {u'filterable': True,
                                   u'label': u'Last name',
                                   u'type': u'string'},
                    u'ldap_dn': {u'label': u'Ldap dn', u'type': u'string'},
                    u'related': {u'help_text': u'Data structure with URLs of related resources.',
                                 u'label': u'Related',
                                 u'type': u'object'},
                    u'summary_fields': {u'help_text': u'Data structure with name/description for related resources.',
                                        u'label': u'Summary fields',
                                        u'type': u'object'},
                    u'type': {u'choices': [[u'user', u'User']],
                              u'help_text': u'Data type for this user.',
                              u'label': u'Type',
                              u'type': u'choice'},
                    u'url': {u'help_text': u'URL for this user.',
                             u'label': u'Url',
                             u'type': u'string'},
                    u'username': {u'filterable': True,
                                  u'help_text': u'Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.',
                                  u'label': u'Username',
                                  u'type': u'string'}}}
renders = [u'application/json', u'text/html']
max_page_size = 200
types = [u'user']
