endpoint = "projects"
name = u'Project List'
related_search_fields = [u'notification_templates_error__search',
                         u'unifiedjob_unified_jobs__search',
                         u'current_job__search',
                         u'credential__search',
                         u'modified_by__search',
                         u'schedules__search',
                         u'credentials__search',
                         u'jobs__search',
                         u'unifiedjobtemplate_ptr__search',
                         u'labels__search',
                         u'next_schedule__search',
                         u'organization__search',
                         u'notification_templates_any__search',
                         u'workflowjobtemplatenodes__search',
                         u'project_updates__search',
                         u'created_by__search',
                         u'scm_inventory_sources__search',
                         u'notification_templates_success__search',
                         u'instance_groups__search',
                         u'jobtemplates__search',
                         u'workflowjobnodes__search',
                         u'last_job__search']
parses = [u'application/json']
search_fields = [u'description', u'name']
actions = {u'GET': {u'created': {u'filterable': True,
                                 u'help_text': u'Timestamp when this project was created.',
                                 u'label': u'Created',
                                 u'type': u'datetime'},
                    u'credential': {u'filterable': True,
                                    u'label': u'Credential',
                                    u'type': u'field'},
                    u'custom_virtualenv': {u'filterable': True,
                                           u'help_text': u'Local absolute file path containing a custom Python virtualenv to use',
                                           u'label': u'Custom virtualenv',
                                           u'type': u'string'},
                    u'description': {u'filterable': True,
                                     u'help_text': u'Optional description of this project.',
                                     u'label': u'Description',
                                     u'type': u'string'},
                    u'id': {u'filterable': True,
                            u'help_text': u'Database ID for this project.',
                            u'label': u'ID',
                            u'type': u'integer'},
                    u'last_job_failed': {u'filterable': True,
                                         u'label': u'Last job failed',
                                         u'type': u'boolean'},
                    u'last_job_run': {u'filterable': True,
                                      u'label': u'Last job run',
                                      u'type': u'datetime'},
                    u'last_update_failed': {u'label': u'Last update failed',
                                            u'type': u'boolean'},
                    u'last_updated': {u'label': u'Last updated', u'type': u'datetime'},
                    u'local_path': {u'filterable': True,
                                    u'help_text': u'Local path (relative to PROJECTS_ROOT) containing playbooks and related files for this project.',
                                    u'label': u'Local path',
                                    u'type': u'string'},
                    u'modified': {u'filterable': True,
                                  u'help_text': u'Timestamp when this project was last modified.',
                                  u'label': u'Modified',
                                  u'type': u'datetime'},
                    u'name': {u'filterable': True,
                              u'help_text': u'Name of this project.',
                              u'label': u'Name',
                              u'type': u'string'},
                    u'next_job_run': {u'filterable': True,
                                      u'label': u'Next job run',
                                      u'type': u'datetime'},
                    u'organization': {u'filterable': True,
                                      u'label': u'Organization',
                                      u'type': u'field'},
                    u'related': {u'help_text': u'Data structure with URLs of related resources.',
                                 u'label': u'Related',
                                 u'type': u'object'},
                    u'scm_branch': {u'filterable': True,
                                    u'help_text': u'Specific branch, tag or commit to checkout.',
                                    u'label': u'SCM Branch',
                                    u'type': u'string'},
                    u'scm_clean': {u'filterable': True,
                                   u'help_text': u'Discard any local changes before syncing the project.',
                                   u'label': u'Scm clean',
                                   u'type': u'boolean'},
                    u'scm_delete_on_next_update': {u'filterable': True,
                                                   u'help_text': u'This field has been deprecated and will be removed in a future release',
                                                   u'label': u'Scm delete on next update',
                                                   u'type': u'boolean'},
                    u'scm_delete_on_update': {u'filterable': True,
                                              u'help_text': u'Delete the project before syncing.',
                                              u'label': u'Scm delete on update',
                                              u'type': u'boolean'},
                    u'scm_revision': {u'filterable': True,
                                      u'help_text': u'The last revision fetched by a project update',
                                      u'label': u'SCM Revision',
                                      u'type': u'string'},
                    u'scm_type': {u'choices': [[u'', u'Manual'],
                                               [u'git', u'Git'],
                                               [u'hg', u'Mercurial'],
                                               [u'svn', u'Subversion'],
                                               [u'insights', u'Red Hat Insights']],
                                  u'filterable': True,
                                  u'help_text': u'Specifies the source control system used to store the project.',
                                  u'label': u'SCM Type',
                                  u'type': u'choice'},
                    u'scm_update_cache_timeout': {u'filterable': True,
                                                  u'help_text': u'The number of seconds after the last project update ran that a newproject update will be launched as a job dependency.',
                                                  u'label': u'Scm update cache timeout',
                                                  u'max_value': 2147483647,
                                                  u'min_value': 0,
                                                  u'type': u'integer'},
                    u'scm_update_on_launch': {u'filterable': True,
                                              u'help_text': u'Update the project when a job is launched that uses the project.',
                                              u'label': u'Scm update on launch',
                                              u'type': u'boolean'},
                    u'scm_url': {u'filterable': True,
                                 u'help_text': u'The location where the project is stored.',
                                 u'label': u'SCM URL',
                                 u'type': u'string'},
                    u'status': {u'choices': [[u'new', u'New'],
                                             [u'pending', u'Pending'],
                                             [u'waiting', u'Waiting'],
                                             [u'running', u'Running'],
                                             [u'successful', u'Successful'],
                                             [u'failed', u'Failed'],
                                             [u'error', u'Error'],
                                             [u'canceled', u'Canceled'],
                                             [u'never updated', u'Never Updated'],
                                             [u'ok', u'OK'],
                                             [u'missing', u'Missing']],
                                u'filterable': True,
                                u'label': u'Status',
                                u'type': u'choice'},
                    u'summary_fields': {u'help_text': u'Data structure with name/description for related resources.',
                                        u'label': u'Summary fields',
                                        u'type': u'object'},
                    u'timeout': {u'filterable': True,
                                 u'help_text': u'The amount of time (in seconds) to run before the task is canceled.',
                                 u'label': u'Timeout',
                                 u'max_value': 2147483647,
                                 u'min_value': -2147483648,
                                 u'type': u'integer'},
                    u'type': {u'choices': [[u'project', u'Project']],
                              u'help_text': u'Data type for this project.',
                              u'label': u'Type',
                              u'type': u'choice'},
                    u'url': {u'help_text': u'URL for this project.',
                             u'label': u'Url',
                             u'type': u'string'}},
           u'POST': {u'credential': {u'filterable': True,
                                     u'label': u'Credential',
                                     u'required': False,
                                     u'type': u'field'},
                     u'custom_virtualenv': {u'default': None,
                                            u'filterable': True,
                                            u'help_text': u'Local absolute file path containing a custom Python virtualenv to use',
                                            u'label': u'Custom virtualenv',
                                            u'max_length': 100,
                                            u'required': False,
                                            u'type': u'string'},
                     u'description': {u'default': u'',
                                      u'filterable': True,
                                      u'help_text': u'Optional description of this project.',
                                      u'label': u'Description',
                                      u'required': False,
                                      u'type': u'string'},
                     u'local_path': {u'filterable': True,
                                     u'help_text': u'Local path (relative to PROJECTS_ROOT) containing playbooks and related files for this project.',
                                     u'label': u'Local path',
                                     u'max_length': 1024,
                                     u'required': False,
                                     u'type': u'string'},
                     u'name': {u'filterable': True,
                               u'help_text': u'Name of this project.',
                               u'label': u'Name',
                               u'max_length': 512,
                               u'required': True,
                               u'type': u'string'},
                     u'organization': {u'filterable': True,
                                       u'label': u'Organization',
                                       u'required': False,
                                       u'type': u'field'},
                     u'scm_branch': {u'default': u'',
                                     u'filterable': True,
                                     u'help_text': u'Specific branch, tag or commit to checkout.',
                                     u'label': u'SCM Branch',
                                     u'max_length': 256,
                                     u'required': False,
                                     u'type': u'string'},
                     u'scm_clean': {u'default': False,
                                    u'filterable': True,
                                    u'help_text': u'Discard any local changes before syncing the project.',
                                    u'label': u'Scm clean',
                                    u'required': False,
                                    u'type': u'boolean'},
                     u'scm_delete_on_update': {u'default': False,
                                               u'filterable': True,
                                               u'help_text': u'Delete the project before syncing.',
                                               u'label': u'Scm delete on update',
                                               u'required': False,
                                               u'type': u'boolean'},
                     u'scm_type': {u'choices': [[u'', u'Manual'],
                                                [u'git', u'Git'],
                                                [u'hg', u'Mercurial'],
                                                [u'svn', u'Subversion'],
                                                [u'insights', u'Red Hat Insights']],
                                   u'default': u'',
                                   u'filterable': True,
                                   u'help_text': u'Specifies the source control system used to store the project.',
                                   u'label': u'SCM Type',
                                   u'required': False,
                                   u'type': u'choice'},
                     u'scm_update_cache_timeout': {u'default': 0,
                                                   u'filterable': True,
                                                   u'help_text': u'The number of seconds after the last project update ran that a newproject update will be launched as a job dependency.',
                                                   u'label': u'Scm update cache timeout',
                                                   u'max_value': 2147483647,
                                                   u'min_value': 0,
                                                   u'required': False,
                                                   u'type': u'integer'},
                     u'scm_update_on_launch': {u'default': False,
                                               u'filterable': True,
                                               u'help_text': u'Update the project when a job is launched that uses the project.',
                                               u'label': u'Scm update on launch',
                                               u'required': False,
                                               u'type': u'boolean'},
                     u'scm_url': {u'default': u'',
                                  u'filterable': True,
                                  u'help_text': u'The location where the project is stored.',
                                  u'label': u'SCM URL',
                                  u'max_length': 1024,
                                  u'required': False,
                                  u'type': u'string'},
                     u'timeout': {u'default': 0,
                                  u'filterable': True,
                                  u'help_text': u'The amount of time (in seconds) to run before the task is canceled.',
                                  u'label': u'Timeout',
                                  u'max_value': 2147483647,
                                  u'min_value': -2147483648,
                                  u'required': False,
                                  u'type': u'integer'}}}
renders = [u'application/json', u'text/html']
max_page_size = 200
types = [u'project']
