endpoint = "workflow_job_template_nodes"
name = u'Workflow Job Template Node List'
related_search_fields = [u'always_nodes__search',
                         u'failure_nodes__search',
                         u'inventory__search',
                         u'unified_job_template__search',
                         u'workflowjobtemplatenodes_success__search',
                         u'success_nodes__search',
                         u'credentials__search',
                         u'workflowjobtemplatenodes_failure__search',
                         u'workflowjobtemplatenodes_always__search',
                         u'workflow_job_template__search']
parses = [u'application/json']
search_fields = [u'unified_job_template__name',
                 u'unified_job_template__description']
actions = {u'GET': {u'always_nodes': {u'label': u'Always nodes', u'type': u'field'},
                    u'created': {u'filterable': True,
                                 u'help_text': u'Timestamp when this workflow job template node was created.',
                                 u'label': u'Created',
                                 u'type': u'datetime'},
                    u'credential': {u'help_text': u'This resource has been deprecated and will be removed in a future release',
                                    u'label': u'Credential',
                                    u'min_value': 1,
                                    u'type': u'integer'},
                    u'diff_mode': {u'label': u'Diff mode', u'type': u'boolean'},
                    u'extra_data': {u'filterable': True,
                                    u'label': u'Extra data',
                                    u'type': u'field'},
                    u'failure_nodes': {u'label': u'Failure nodes', u'type': u'field'},
                    u'id': {u'filterable': True,
                            u'help_text': u'Database ID for this workflow job template node.',
                            u'label': u'ID',
                            u'type': u'integer'},
                    u'inventory': {u'filterable': True,
                                   u'label': u'Inventory',
                                   u'type': u'field'},
                    u'job_tags': {u'label': u'Job tags', u'type': u'string'},
                    u'job_type': {u'choices': [[u'run', u'Run'], [u'check', u'Check']],
                                  u'label': u'Job type',
                                  u'type': u'choice'},
                    u'limit': {u'label': u'Limit', u'type': u'string'},
                    u'modified': {u'filterable': True,
                                  u'help_text': u'Timestamp when this workflow job template node was last modified.',
                                  u'label': u'Modified',
                                  u'type': u'datetime'},
                    u'related': {u'help_text': u'Data structure with URLs of related resources.',
                                 u'label': u'Related',
                                 u'type': u'object'},
                    u'skip_tags': {u'label': u'Skip tags', u'type': u'string'},
                    u'success_nodes': {u'label': u'Success nodes', u'type': u'field'},
                    u'summary_fields': {u'help_text': u'Data structure with name/description for related resources.',
                                        u'label': u'Summary fields',
                                        u'type': u'object'},
                    u'type': {u'choices': [[u'workflow_job_template_node',
                                            u'Workflow Job Template Node']],
                              u'help_text': u'Data type for this workflow job template node.',
                              u'label': u'Type',
                              u'type': u'choice'},
                    u'unified_job_template': {u'filterable': True,
                                              u'label': u'Unified job template',
                                              u'type': u'field'},
                    u'url': {u'help_text': u'URL for this workflow job template node.',
                             u'label': u'Url',
                             u'type': u'string'},
                    u'verbosity': {u'choices': [[0, u'0 (Normal)'],
                                                [1, u'1 (Verbose)'],
                                                [2, u'2 (More Verbose)'],
                                                [3, u'3 (Debug)'],
                                                [4, u'4 (Connection Debug)'],
                                                [5, u'5 (WinRM Debug)']],
                                   u'label': u'Verbosity',
                                   u'type': u'choice'},
                    u'workflow_job_template': {u'filterable': True,
                                               u'label': u'Workflow job template',
                                               u'type': u'field'}},
           u'POST': {u'credential': {u'default': None,
                                     u'help_text': u'This resource has been deprecated and will be removed in a future release',
                                     u'label': u'Credential',
                                     u'min_value': 1,
                                     u'required': False,
                                     u'type': u'integer'},
                     u'diff_mode': {u'default': None,
                                    u'label': u'Diff mode',
                                    u'required': False,
                                    u'type': u'boolean'},
                     u'extra_data': {u'default': {},
                                     u'filterable': True,
                                     u'label': u'Extra data',
                                     u'required': False,
                                     u'type': u'field'},
                     u'inventory': {u'filterable': True,
                                    u'label': u'Inventory',
                                    u'required': False,
                                    u'type': u'field'},
                     u'job_tags': {u'default': None,
                                   u'label': u'Job tags',
                                   u'required': False,
                                   u'type': u'string'},
                     u'job_type': {u'choices': [[u'run', u'Run'], [u'check', u'Check']],
                                   u'default': None,
                                   u'label': u'Job type',
                                   u'required': False,
                                   u'type': u'choice'},
                     u'limit': {u'default': None,
                                u'label': u'Limit',
                                u'required': False,
                                u'type': u'string'},
                     u'skip_tags': {u'default': None,
                                    u'label': u'Skip tags',
                                    u'required': False,
                                    u'type': u'string'},
                     u'unified_job_template': {u'filterable': True,
                                               u'label': u'Unified job template',
                                               u'required': False,
                                               u'type': u'field'},
                     u'verbosity': {u'choices': [[0, u'0 (Normal)'],
                                                 [1, u'1 (Verbose)'],
                                                 [2, u'2 (More Verbose)'],
                                                 [3, u'3 (Debug)'],
                                                 [4, u'4 (Connection Debug)'],
                                                 [5, u'5 (WinRM Debug)']],
                                    u'default': None,
                                    u'label': u'Verbosity',
                                    u'required': False,
                                    u'type': u'choice'},
                     u'workflow_job_template': {u'filterable': True,
                                                u'label': u'Workflow job template',
                                                u'required': True,
                                                u'type': u'field'}}}
renders = [u'application/json', u'text/html']
max_page_size = 200
types = [u'workflow_job_template_node']
