endpoint = u'project_updates'
name = u'Project Update List'
related_search_fields = [u'project_update_events__search',
                         u'schedule__search',
                         u'modified_by__search',
                         u'notifications__search',
                         u'project__search',
                         u'unified_job_template__search',
                         u'scm_inventory_updates__search',
                         u'unified_job_node__search',
                         u'unifiedjob_ptr__search',
                         u'instance_group__search',
                         u'credentials__search',
                         u'credential__search',
                         u'dependent_jobs__search',
                         u'launch_config__search',
                         u'job_origin__search',
                         u'created_by__search',
                         u'labels__search']
parses = [u'application/json']
search_fields = [u'description', u'name']
actions = {u'GET': {u'controller_node': {u'filterable': True,
                                         u'help_text': u'The instance that managed the isolated execution environment.',
                                         u'label': u'Controller node',
                                         u'type': u'string'},
                    u'created': {u'filterable': True,
                                 u'help_text': u'Timestamp when this project update was created.',
                                 u'label': u'Created',
                                 u'type': u'datetime'},
                    u'credential': {u'filterable': True,
                                    u'label': u'Credential',
                                    u'type': u'field'},
                    u'description': {u'filterable': True,
                                     u'help_text': u'Optional description of this project update.',
                                     u'label': u'Description',
                                     u'type': u'string'},
                    u'elapsed': {u'filterable': True,
                                 u'help_text': u'Elapsed time in seconds that the job ran.',
                                 u'label': u'Elapsed',
                                 u'type': u'decimal'},
                    u'execution_node': {u'filterable': True,
                                        u'help_text': u'The node the job executed on.',
                                        u'label': u'Execution node',
                                        u'type': u'string'},
                    u'failed': {u'filterable': True,
                                u'label': u'Failed',
                                u'type': u'boolean'},
                    u'finished': {u'filterable': True,
                                  u'help_text': u'The date and time the job finished execution.',
                                  u'label': u'Finished',
                                  u'type': u'datetime'},
                    u'id': {u'filterable': True,
                            u'help_text': u'Database ID for this project update.',
                            u'label': u'ID',
                            u'type': u'integer'},
                    u'job_explanation': {u'filterable': True,
                                         u'help_text': u"A status field to indicate the state of the job if it wasn't able to run and capture stdout",
                                         u'label': u'Job explanation',
                                         u'type': u'string'},
                    u'job_type': {u'choices': [[u'run', u'Run'], [u'check', u'Check']],
                                  u'filterable': True,
                                  u'label': u'Job type',
                                  u'type': u'choice'},
                    u'launch_type': {u'choices': [[u'manual', u'Manual'],
                                                  [u'relaunch', u'Relaunch'],
                                                  [u'callback', u'Callback'],
                                                  [u'scheduled', u'Scheduled'],
                                                  [u'dependency', u'Dependency'],
                                                  [u'workflow', u'Workflow'],
                                                  [u'sync', u'Sync'],
                                                  [u'scm', u'SCM Update']],
                                     u'filterable': True,
                                     u'label': u'Launch type',
                                     u'type': u'choice'},
                    u'local_path': {u'filterable': True,
                                    u'help_text': u'Local path (relative to PROJECTS_ROOT) containing playbooks and related files for this project.',
                                    u'label': u'Local path',
                                    u'type': u'string'},
                    u'modified': {u'filterable': True,
                                  u'help_text': u'Timestamp when this project update was last modified.',
                                  u'label': u'Modified',
                                  u'type': u'datetime'},
                    u'name': {u'filterable': True,
                              u'help_text': u'Name of this project update.',
                              u'label': u'Name',
                              u'type': u'string'},
                    u'project': {u'filterable': True,
                                 u'label': u'Project',
                                 u'type': u'field'},
                    u'related': {u'help_text': u'Data structure with URLs of related resources.',
                                 u'label': u'Related',
                                 u'type': u'object'},
                    u'scm_branch': {u'filterable': True,
                                    u'help_text': u'Specific branch, tag or commit to checkout.',
                                    u'label': u'SCM Branch',
                                    u'type': u'string'},
                    u'scm_clean': {u'filterable': True,
                                   u'help_text': u'Discard any local changes before syncing the project.',
                                   u'label': u'Scm clean',
                                   u'type': u'boolean'},
                    u'scm_delete_on_update': {u'filterable': True,
                                              u'help_text': u'Delete the project before syncing.',
                                              u'label': u'Scm delete on update',
                                              u'type': u'boolean'},
                    u'scm_type': {u'choices': [[u'', u'Manual'],
                                               [u'git', u'Git'],
                                               [u'hg', u'Mercurial'],
                                               [u'svn', u'Subversion'],
                                               [u'insights', u'Red Hat Insights']],
                                  u'filterable': True,
                                  u'help_text': u'Specifies the source control system used to store the project.',
                                  u'label': u'SCM Type',
                                  u'type': u'choice'},
                    u'scm_url': {u'filterable': True,
                                 u'help_text': u'The location where the project is stored.',
                                 u'label': u'SCM URL',
                                 u'type': u'string'},
                    u'started': {u'filterable': True,
                                 u'help_text': u'The date and time the job was queued for starting.',
                                 u'label': u'Started',
                                 u'type': u'datetime'},
                    u'status': {u'choices': [[u'new', u'New'],
                                             [u'pending', u'Pending'],
                                             [u'waiting', u'Waiting'],
                                             [u'running', u'Running'],
                                             [u'successful', u'Successful'],
                                             [u'failed', u'Failed'],
                                             [u'error', u'Error'],
                                             [u'canceled', u'Canceled']],
                                u'filterable': True,
                                u'label': u'Status',
                                u'type': u'choice'},
                    u'summary_fields': {u'help_text': u'Data structure with name/description for related resources.',
                                        u'label': u'Summary fields',
                                        u'type': u'object'},
                    u'timeout': {u'filterable': True,
                                 u'help_text': u'The amount of time (in seconds) to run before the task is canceled.',
                                 u'label': u'Timeout',
                                 u'max_value': 2147483647,
                                 u'min_value': -2147483648,
                                 u'type': u'integer'},
                    u'type': {u'choices': [[u'project_update', u'SCM Update']],
                              u'help_text': u'Data type for this project update.',
                              u'label': u'Type',
                              u'type': u'choice'},
                    u'unified_job_template': {u'filterable': True,
                                              u'label': u'unified job template',
                                              u'type': u'field'},
                    u'url': {u'help_text': u'URL for this project update.',
                             u'label': u'Url',
                             u'type': u'string'}}}
renders = [u'application/json', u'text/html']
max_page_size = 200
types = [u'project_update']
