endpoint = "credentials"
name = u'Credential List'
related_search_fields = [u'modified_by__search',
                         u'credential_type__search',
                         u'schedules__search',
                         u'ad_hoc_commands__search',
                         u'workflowjobnodes__search',
                         u'projects__search',
                         u'unifiedjobs__search',
                         u'unifiedjobtemplates__search',
                         u'workflowjobtemplatenodes__search',
                         u'insights_inventories__search',
                         u'projectupdates__search',
                         u'created_by__search',
                         u'joblaunchconfigs__search',
                         u'organization__search']
parses = [u'application/json']
search_fields = [u'description', u'name']
actions = {u'GET': {u'created': {u'filterable': True,
                                 u'help_text': u'Timestamp when this credential was created.',
                                 u'label': u'Created',
                                 u'type': u'datetime'},
                    u'credential_type': {u'filterable': True,
                                         u'help_text': u'Specify the type of credential you want to create. Refer to the Ansible Tower documentation for details on each type.',
                                         u'label': u'Credential type',
                                         u'type': u'field'},
                    u'description': {u'filterable': True,
                                     u'help_text': u'Optional description of this credential.',
                                     u'label': u'Description',
                                     u'type': u'string'},
                    u'id': {u'filterable': True,
                            u'help_text': u'Database ID for this credential.',
                            u'label': u'ID',
                            u'type': u'integer'},
                    u'inputs': {u'filterable': True,
                                u'help_text': u'Enter inputs using either JSON or YAML syntax. Use the radio button to toggle between the two. Refer to the Ansible Tower documentation for example syntax.',
                                u'label': u'Inputs',
                                u'type': u'field'},
                    u'modified': {u'filterable': True,
                                  u'help_text': u'Timestamp when this credential was last modified.',
                                  u'label': u'Modified',
                                  u'type': u'datetime'},
                    u'name': {u'filterable': True,
                              u'help_text': u'Name of this credential.',
                              u'label': u'Name',
                              u'type': u'string'},
                    u'organization': {u'filterable': True,
                                      u'help_text': u'Inherit permissions from organization roles. If provided on creation, do not give either user or team.',
                                      u'label': u'Organization',
                                      u'type': u'field'},
                    u'related': {u'help_text': u'Data structure with URLs of related resources.',
                                 u'label': u'Related',
                                 u'type': u'object'},
                    u'summary_fields': {u'help_text': u'Data structure with name/description for related resources.',
                                        u'label': u'Summary fields',
                                        u'type': u'object'},
                    u'type': {u'choices': [[u'credential', u'Credential']],
                              u'help_text': u'Data type for this credential.',
                              u'label': u'Type',
                              u'type': u'choice'},
                    u'url': {u'help_text': u'URL for this credential.',
                             u'label': u'Url',
                             u'type': u'string'}},
           u'POST': {u'credential_type': {u'filterable': True,
                                          u'help_text': u'Specify the type of credential you want to create. Refer to the Ansible Tower documentation for details on each type.',
                                          u'label': u'Credential type',
                                          u'required': True,
                                          u'type': u'field'},
                     u'description': {u'default': u'',
                                      u'filterable': True,
                                      u'help_text': u'Optional description of this credential.',
                                      u'label': u'Description',
                                      u'required': False,
                                      u'type': u'string'},
                     u'inputs': {u'default': {},
                                 u'filterable': True,
                                 u'help_text': u'Enter inputs using either JSON or YAML syntax. Use the radio button to toggle between the two. Refer to the Ansible Tower documentation for example syntax.',
                                 u'label': u'Inputs',
                                 u'required': False,
                                 u'type': u'field'},
                     u'name': {u'filterable': True,
                               u'help_text': u'Name of this credential.',
                               u'label': u'Name',
                               u'max_length': 512,
                               u'required': True,
                               u'type': u'string'},
                     u'organization': {u'default': None,
                                       u'filterable': True,
                                       u'help_text': u'Inherit permissions from organization roles. If provided on creation, do not give either user or team.',
                                       u'label': u'Organization',
                                       u'required': False,
                                       u'type': u'field'},
                     u'team': {u'default': None,
                               u'help_text': u'Write-only field used to add team to owner role. If provided, do not give either user or organization. Only valid for creation.',
                               u'label': u'Team',
                               u'required': False,
                               u'type': u'field',
                               u'write_only': True},
                     u'user': {u'default': None,
                               u'help_text': u'Write-only field used to add user to owner role. If provided, do not give either team or organization. Only valid for creation.',
                               u'label': u'User',
                               u'required': False,
                               u'type': u'field',
                               u'write_only': True}}}
renders = [u'application/json', u'text/html']
max_page_size = 200
types = [u'credential']
