endpoint = "notifications"
name = u'Notification List'
related_search_fields = [
    u'notification_template__search', u'unifiedjob_notifications__search']
parses = [u'application/json']
search_fields = [u'subject', u'notification_type', u'body']
actions = {u'GET': {u'created': {u'filterable': True,
                                 u'help_text': u'Timestamp when this notification was created.',
                                 u'label': u'Created',
                                 u'type': u'datetime'},
                    u'error': {u'filterable': True,
                               u'label': u'Error',
                               u'type': u'string'},
                    u'id': {u'filterable': True,
                            u'help_text': u'Database ID for this notification.',
                            u'label': u'ID',
                            u'type': u'integer'},
                    u'modified': {u'filterable': True,
                                  u'help_text': u'Timestamp when this notification was last modified.',
                                  u'label': u'Modified',
                                  u'type': u'datetime'},
                    u'notification_template': {u'filterable': True,
                                               u'label': u'Notification template',
                                               u'type': u'field'},
                    u'notification_type': {u'choices': [[u'email', u'Email'],
                                                        [u'slack', u'Slack'],
                                                        [u'twilio', u'Twilio'],
                                                        [u'pagerduty',
                                                            u'Pagerduty'],
                                                        [u'hipchat', u'HipChat'],
                                                        [u'webhook', u'Webhook'],
                                                        [u'mattermost',
                                                            u'Mattermost'],
                                                        [u'rocketchat',
                                                            u'Rocket.Chat'],
                                                        [u'irc', u'IRC']],
                                           u'filterable': True,
                                           u'label': u'Notification type',
                                           u'type': u'choice'},
                    u'notifications_sent': {u'filterable': True,
                                            u'label': u'Notifications sent',
                                            u'type': u'integer'},
                    u'recipients': {u'filterable': True,
                                    u'label': u'Recipients',
                                    u'type': u'string'},
                    u'related': {u'help_text': u'Data structure with URLs of related resources.',
                                 u'label': u'Related',
                                 u'type': u'object'},
                    u'status': {u'choices': [[u'pending', u'Pending'],
                                             [u'successful', u'Successful'],
                                             [u'failed', u'Failed']],
                                u'filterable': True,
                                u'label': u'Status',
                                u'type': u'choice'},
                    u'subject': {u'filterable': True,
                                 u'label': u'Subject',
                                 u'type': u'string'},
                    u'summary_fields': {u'help_text': u'Data structure with name/description for related resources.',
                                        u'label': u'Summary fields',
                                        u'type': u'object'},
                    u'type': {u'choices': [[u'notification', u'Notification']],
                              u'help_text': u'Data type for this notification.',
                              u'label': u'Type',
                              u'type': u'choice'},
                    u'url': {u'help_text': u'URL for this notification.',
                             u'label': u'Url',
                             u'type': u'string'}}}
renders = [u'application/json', u'text/html']
max_page_size = 200
types = [u'notification']
