endpoint = "tokens"
name = u'OAuth2 Tokens'
related_search_fields = [u'user__search',
                         u'refresh_token__search', u'application__search']
parses = [u'application/json']
search_fields = [u'description']
actions = {u'GET': {u'application': {u'filterable': True,
                                     u'label': u'Application',
                                     u'type': u'field'},
                    u'created': {u'filterable': True,
                                 u'help_text': u'Timestamp when this access token was created.',
                                 u'label': u'Created',
                                 u'type': u'datetime'},
                    u'description': {u'filterable': True,
                                     u'help_text': u'Optional description of this access token.',
                                     u'label': u'Description',
                                     u'type': u'string'},
                    u'expires': {u'filterable': True,
                                 u'label': u'Expires',
                                 u'type': u'datetime'},
                    u'id': {u'filterable': True,
                            u'help_text': u'Database ID for this access token.',
                            u'label': u'Id',
                            u'type': u'integer'},
                    u'modified': {u'help_text': u'Timestamp when this access token was last modified.',
                                  u'label': u'Modified',
                                  u'type': u'datetime'},
                    u'refresh_token': {u'label': u'Refresh token', u'type': u'field'},
                    u'related': {u'help_text': u'Data structure with URLs of related resources.',
                                 u'label': u'Related',
                                 u'type': u'object'},
                    u'scope': {u'filterable': True,
                               u'help_text': u"Allowed scopes, further restricts user's permissions. Must be a simple space-separated string with allowed scopes ['read', 'write'].",
                               u'label': u'Scope',
                               u'type': u'string'},
                    u'summary_fields': {u'help_text': u'Data structure with name/description for related resources.',
                                        u'label': u'Summary fields',
                                        u'type': u'object'},
                    u'token': {u'filterable': True,
                               u'label': u'Token',
                               u'type': u'field'},
                    u'type': {u'choices': [[u'o_auth2_access_token', u'Access Token']],
                              u'help_text': u'Data type for this access token.',
                              u'label': u'Type',
                              u'type': u'choice'},
                    u'url': {u'help_text': u'URL for this access token.',
                             u'label': u'Url',
                             u'type': u'string'},
                    u'user': {u'filterable': True,
                              u'help_text': u'The user representing the token owner',
                              u'label': u'User',
                              u'type': u'field'}},
           u'POST': {u'application': {u'filterable': True,
                                      u'label': u'Application',
                                      u'required': False,
                                      u'type': u'field'},
                     u'description': {u'default': u'',
                                      u'filterable': True,
                                      u'help_text': u'Optional description of this access token.',
                                      u'label': u'Description',
                                      u'max_length': 200,
                                      u'required': False,
                                      u'type': u'string'},
                     u'scope': {u'default': u'write',
                                u'filterable': True,
                                u'help_text': u"Allowed scopes, further restricts user's permissions. Must be a simple space-separated string with allowed scopes ['read', 'write'].",
                                u'label': u'Scope',
                                u'required': False,
                                u'type': u'string'}}}
renders = [u'application/json', u'text/html']
max_page_size = 200
types = [u'o_auth2_access_token']
