endpoint = u'workflow_job_nodes'
name = u'Workflow Job Node List'
related_search_fields = [u'workflowjobnodes_always__search',
                         u'inventory__search',
                         u'unified_job_template__search',
                         u'always_nodes__search',
                         u'workflowjobnodes_failure__search',
                         u'credentials__search',
                         u'job__search',
                         u'workflow_job__search',
                         u'success_nodes__search',
                         u'workflowjobnodes_success__search',
                         u'failure_nodes__search']
parses = [u'application/json']
search_fields = [u'unified_job_template__name',
                 u'unified_job_template__description']
actions = {u'GET': {u'always_nodes': {u'label': u'Always nodes', u'type': u'field'},
                    u'created': {u'filterable': True,
                                 u'help_text': u'Timestamp when this workflow job node was created.',
                                 u'label': u'Created',
                                 u'type': u'datetime'},
                    u'credential': {u'help_text': u'This resource has been deprecated and will be removed in a future release',
                                    u'label': u'Credential',
                                    u'min_value': 1,
                                    u'type': u'integer'},
                    u'diff_mode': {u'label': u'Diff mode', u'type': u'boolean'},
                    u'extra_data': {u'filterable': True,
                                    u'label': u'Extra data',
                                    u'type': u'field'},
                    u'failure_nodes': {u'label': u'Failure nodes', u'type': u'field'},
                    u'id': {u'filterable': True,
                            u'help_text': u'Database ID for this workflow job node.',
                            u'label': u'ID',
                            u'type': u'integer'},
                    u'inventory': {u'filterable': True,
                                   u'label': u'Inventory',
                                   u'type': u'field'},
                    u'job': {u'filterable': True, u'label': u'Job', u'type': u'field'},
                    u'job_tags': {u'label': u'Job tags', u'type': u'string'},
                    u'job_type': {u'choices': [[u'run', u'Run'], [u'check', u'Check']],
                                  u'label': u'Job type',
                                  u'type': u'choice'},
                    u'limit': {u'label': u'Limit', u'type': u'string'},
                    u'modified': {u'filterable': True,
                                  u'help_text': u'Timestamp when this workflow job node was last modified.',
                                  u'label': u'Modified',
                                  u'type': u'datetime'},
                    u'related': {u'help_text': u'Data structure with URLs of related resources.',
                                 u'label': u'Related',
                                 u'type': u'object'},
                    u'skip_tags': {u'label': u'Skip tags', u'type': u'string'},
                    u'success_nodes': {u'label': u'Success nodes', u'type': u'field'},
                    u'summary_fields': {u'help_text': u'Data structure with name/description for related resources.',
                                        u'label': u'Summary fields',
                                        u'type': u'object'},
                    u'type': {u'choices': [[u'workflow_job_node', u'Workflow Job Node']],
                              u'help_text': u'Data type for this workflow job node.',
                              u'label': u'Type',
                              u'type': u'choice'},
                    u'unified_job_template': {u'filterable': True,
                                              u'label': u'Unified job template',
                                              u'type': u'field'},
                    u'url': {u'help_text': u'URL for this workflow job node.',
                             u'label': u'Url',
                             u'type': u'string'},
                    u'verbosity': {u'choices': [[0, u'0 (Normal)'],
                                                [1, u'1 (Verbose)'],
                                                [2, u'2 (More Verbose)'],
                                                [3, u'3 (Debug)'],
                                                [4, u'4 (Connection Debug)'],
                                                [5, u'5 (WinRM Debug)']],
                                   u'label': u'Verbosity',
                                   u'type': u'choice'},
                    u'workflow_job': {u'filterable': True,
                                      u'label': u'Workflow job',
                                      u'type': u'field'}}}
renders = [u'application/json', u'text/html']
max_page_size = 200
types = [u'workflow_job_node']
