endpoint = u'system_jobs'
name = u'System Job List'
related_search_fields = [u'schedule__search',
                         u'modified_by__search',
                         u'notifications__search',
                         u'system_job_template__search',
                         u'unified_job_template__search',
                         u'unifiedjob_ptr__search',
                         u'instance_group__search',
                         u'credentials__search',
                         u'system_job_events__search',
                         u'unified_job_node__search',
                         u'dependent_jobs__search',
                         u'launch_config__search',
                         u'job_origin__search',
                         u'created_by__search',
                         u'labels__search']
parses = [u'application/json']
search_fields = [u'description', u'name']
actions = {u'GET': {u'controller_node': {u'filterable': True,
                                         u'help_text': u'The instance that managed the isolated execution environment.',
                                         u'label': u'Controller node',
                                         u'type': u'string'},
                    u'created': {u'filterable': True,
                                 u'help_text': u'Timestamp when this system job was created.',
                                 u'label': u'Created',
                                 u'type': u'datetime'},
                    u'description': {u'filterable': True,
                                     u'help_text': u'Optional description of this system job.',
                                     u'label': u'Description',
                                     u'type': u'string'},
                    u'elapsed': {u'filterable': True,
                                 u'help_text': u'Elapsed time in seconds that the job ran.',
                                 u'label': u'Elapsed',
                                 u'type': u'decimal'},
                    u'execution_node': {u'filterable': True,
                                        u'help_text': u'The node the job executed on.',
                                        u'label': u'Execution node',
                                        u'type': u'string'},
                    u'extra_vars': {u'filterable': True,
                                    u'label': u'Extra vars',
                                    u'type': u'string'},
                    u'failed': {u'filterable': True,
                                u'label': u'Failed',
                                u'type': u'boolean'},
                    u'finished': {u'filterable': True,
                                  u'help_text': u'The date and time the job finished execution.',
                                  u'label': u'Finished',
                                  u'type': u'datetime'},
                    u'id': {u'filterable': True,
                            u'help_text': u'Database ID for this system job.',
                            u'label': u'ID',
                            u'type': u'integer'},
                    u'job_explanation': {u'filterable': True,
                                         u'help_text': u"A status field to indicate the state of the job if it wasn't able to run and capture stdout",
                                         u'label': u'Job explanation',
                                         u'type': u'string'},
                    u'job_type': {u'choices': [[u'cleanup_jobs',
                                                u'Remove jobs older than a certain number of days'],
                                               [u'cleanup_activitystream',
                                                u'Remove activity stream entries older than a certain number of days'],
                                               [u'cleanup_facts',
                                                u'Purge and/or reduce the granularity of system tracking data']],
                                  u'filterable': True,
                                  u'label': u'Job type',
                                  u'type': u'choice'},
                    u'launch_type': {u'choices': [[u'manual', u'Manual'],
                                                  [u'relaunch', u'Relaunch'],
                                                  [u'callback', u'Callback'],
                                                  [u'scheduled', u'Scheduled'],
                                                  [u'dependency', u'Dependency'],
                                                  [u'workflow', u'Workflow'],
                                                  [u'sync', u'Sync'],
                                                  [u'scm', u'SCM Update']],
                                     u'filterable': True,
                                     u'label': u'Launch type',
                                     u'type': u'choice'},
                    u'modified': {u'filterable': True,
                                  u'help_text': u'Timestamp when this system job was last modified.',
                                  u'label': u'Modified',
                                  u'type': u'datetime'},
                    u'name': {u'filterable': True,
                              u'help_text': u'Name of this system job.',
                              u'label': u'Name',
                              u'type': u'string'},
                    u'related': {u'help_text': u'Data structure with URLs of related resources.',
                                 u'label': u'Related',
                                 u'type': u'object'},
                    u'result_stdout': {u'label': u'Result stdout', u'type': u'field'},
                    u'started': {u'filterable': True,
                                 u'help_text': u'The date and time the job was queued for starting.',
                                 u'label': u'Started',
                                 u'type': u'datetime'},
                    u'status': {u'choices': [[u'new', u'New'],
                                             [u'pending', u'Pending'],
                                             [u'waiting', u'Waiting'],
                                             [u'running', u'Running'],
                                             [u'successful', u'Successful'],
                                             [u'failed', u'Failed'],
                                             [u'error', u'Error'],
                                             [u'canceled', u'Canceled']],
                                u'filterable': True,
                                u'label': u'Status',
                                u'type': u'choice'},
                    u'summary_fields': {u'help_text': u'Data structure with name/description for related resources.',
                                        u'label': u'Summary fields',
                                        u'type': u'object'},
                    u'system_job_template': {u'filterable': True,
                                             u'label': u'System job template',
                                             u'type': u'field'},
                    u'type': {u'choices': [[u'system_job', u'Management Job']],
                              u'help_text': u'Data type for this system job.',
                              u'label': u'Type',
                              u'type': u'choice'},
                    u'unified_job_template': {u'filterable': True,
                                              u'label': u'unified job template',
                                              u'type': u'field'},
                    u'url': {u'help_text': u'URL for this system job.',
                             u'label': u'Url',
                             u'type': u'string'}},
           u'POST': {u'description': {u'default': u'',
                                      u'filterable': True,
                                      u'help_text': u'Optional description of this system job.',
                                      u'label': u'Description',
                                      u'required': False,
                                      u'type': u'string'},
                     u'extra_vars': {u'default': u'',
                                     u'filterable': True,
                                     u'label': u'Extra vars',
                                     u'required': False,
                                     u'type': u'string'},
                     u'job_type': {u'choices': [[u'cleanup_jobs',
                                                 u'Remove jobs older than a certain number of days'],
                                                [u'cleanup_activitystream',
                                                 u'Remove activity stream entries older than a certain number of days'],
                                                [u'cleanup_facts',
                                                 u'Purge and/or reduce the granularity of system tracking data']],
                                   u'default': u'',
                                   u'filterable': True,
                                   u'label': u'Job type',
                                   u'required': False,
                                   u'type': u'choice'},
                     u'name': {u'filterable': True,
                               u'help_text': u'Name of this system job.',
                               u'label': u'Name',
                               u'max_length': 512,
                               u'required': True,
                               u'type': u'string'},
                     u'system_job_template': {u'filterable': True,
                                              u'label': u'System job template',
                                              u'required': False,
                                              u'type': u'field'}}}
renders = [u'application/json', u'text/html']
max_page_size = 200
types = [u'system_job']
