endpoint = u'inventory'
name = u'Inventory Detail'
parses = [u'application/json']
actions = {u'GET': {u'created': {u'filterable': True,
                                 u'help_text': u'Timestamp when this inventory was created.',
                                 u'label': u'Created',
                                 u'type': u'datetime'},
                    u'description': {u'filterable': True,
                                     u'help_text': u'Optional description of this inventory.',
                                     u'label': u'Description',
                                     u'type': u'string'},
                    u'groups_with_active_failures': {u'filterable': True,
                                                     u'help_text': u'Number of groups in this inventory with active failures.',
                                                     u'label': u'Groups with active failures',
                                                     u'min_value': 0,
                                                     u'type': u'integer'},
                    u'has_active_failures': {u'filterable': True,
                                             u'help_text': u'Flag indicating whether any hosts in this inventory have failed.',
                                             u'label': u'Has active failures',
                                             u'type': u'boolean'},
                    u'has_inventory_sources': {u'filterable': True,
                                               u'help_text': u'Flag indicating whether this inventory has any external inventory sources.',
                                               u'label': u'Has inventory sources',
                                               u'type': u'boolean'},
                    u'host_filter': {u'filterable': True,
                                     u'help_text': u'Filter that will be applied to the hosts of this inventory.',
                                     u'label': u'Host filter',
                                     u'type': u'string'},
                    u'hosts_with_active_failures': {u'filterable': True,
                                                    u'help_text': u'Number of hosts in this inventory with active failures.',
                                                    u'label': u'Hosts with active failures',
                                                    u'min_value': 0,
                                                    u'type': u'integer'},
                    u'id': {u'filterable': True,
                            u'help_text': u'Database ID for this inventory.',
                            u'label': u'ID',
                            u'type': u'integer'},
                    u'insights_credential': {u'filterable': True,
                                             u'help_text': u'Credentials to be used by hosts belonging to this inventory when accessing Red Hat Insights API.',
                                             u'label': u'Insights credential',
                                             u'type': u'field'},
                    u'inventory_sources_with_failures': {u'filterable': True,
                                                         u'help_text': u'Number of external inventory sources in this inventory with failures.',
                                                         u'label': u'Inventory sources with failures',
                                                         u'min_value': 0,
                                                         u'type': u'integer'},
                    u'kind': {u'choices': [[u'',
                                            u'Hosts have a direct link to this inventory.'],
                                           [u'smart',
                                            u'Hosts for inventory generated using the host_filter property.']],
                              u'filterable': True,
                              u'help_text': u'Kind of inventory being represented.',
                              u'label': u'Kind',
                              u'type': u'choice'},
                    u'modified': {u'filterable': True,
                                  u'help_text': u'Timestamp when this inventory was last modified.',
                                  u'label': u'Modified',
                                  u'type': u'datetime'},
                    u'name': {u'filterable': True,
                              u'help_text': u'Name of this inventory.',
                              u'label': u'Name',
                              u'type': u'string'},
                    u'organization': {u'filterable': True,
                                      u'help_text': u'Organization containing this inventory.',
                                      u'label': u'Organization',
                                      u'type': u'field'},
                    u'pending_deletion': {u'filterable': True,
                                          u'help_text': u'Flag indicating the inventory is being deleted.',
                                          u'label': u'Pending deletion',
                                          u'type': u'boolean'},
                    u'related': {u'help_text': u'Data structure with URLs of related resources.',
                                 u'label': u'Related',
                                 u'type': u'object'},
                    u'summary_fields': {u'help_text': u'Data structure with name/description for related resources.',
                                        u'label': u'Summary fields',
                                        u'type': u'object'},
                    u'total_groups': {u'filterable': True,
                                      u'help_text': u'Total number of groups in this inventory.',
                                      u'label': u'Total groups',
                                      u'min_value': 0,
                                      u'type': u'integer'},
                    u'total_hosts': {u'filterable': True,
                                     u'help_text': u'Total number of hosts in this inventory.',
                                     u'label': u'Total hosts',
                                     u'min_value': 0,
                                     u'type': u'integer'},
                    u'total_inventory_sources': {u'filterable': True,
                                                 u'help_text': u'Total number of external inventory sources configured within this inventory.',
                                                 u'label': u'Total inventory sources',
                                                 u'min_value': 0,
                                                 u'type': u'integer'},
                    u'type': {u'choices': [[u'inventory', u'Inventory']],
                              u'help_text': u'Data type for this inventory.',
                              u'label': u'Type',
                              u'type': u'choice'},
                    u'url': {u'help_text': u'URL for this inventory.',
                             u'label': u'Url',
                             u'type': u'string'},
                    u'variables': {u'filterable': True,
                                   u'help_text': u'Inventory variables in JSON or YAML format.',
                                   u'label': u'Variables',
                                   u'type': u'string'}},
           u'PUT': {u'description': {u'default': u'',
                                     u'filterable': True,
                                     u'help_text': u'Optional description of this inventory.',
                                     u'label': u'Description',
                                     u'required': False,
                                     u'type': u'string'},
                    u'host_filter': {u'default': None,
                                     u'filterable': True,
                                     u'help_text': u'Filter that will be applied to the hosts of this inventory.',
                                     u'label': u'Host filter',
                                     u'required': False,
                                     u'type': u'string'},
                    u'insights_credential': {u'filterable': True,
                                             u'help_text': u'Credentials to be used by hosts belonging to this inventory when accessing Red Hat Insights API.',
                                             u'label': u'Insights credential',
                                             u'required': False,
                                             u'type': u'field'},
                    u'kind': {u'choices': [[u'',
                                            u'Hosts have a direct link to this inventory.'],
                                           [u'smart',
                                            u'Hosts for inventory generated using the host_filter property.']],
                              u'default': u'',
                              u'filterable': True,
                              u'help_text': u'Kind of inventory being represented.',
                              u'label': u'Kind',
                              u'required': False,
                              u'type': u'choice'},
                    u'name': {u'filterable': True,
                              u'help_text': u'Name of this inventory.',
                              u'label': u'Name',
                              u'max_length': 512,
                              u'required': True,
                              u'type': u'string'},
                    u'organization': {u'filterable': True,
                                      u'help_text': u'Organization containing this inventory.',
                                      u'label': u'Organization',
                                      u'required': True,
                                      u'type': u'field'},
                    u'variables': {u'default': u'',
                                   u'filterable': True,
                                   u'help_text': u'Inventory variables in JSON or YAML format.',
                                   u'label': u'Variables',
                                   u'required': False,
                                   u'type': u'string'}}}
renders = [u'application/json', u'text/html']
types = [u'inventory']
